from typing import List, Dict, Any, Iterator
from pathlib import Path
from fastavro import writer, reader, parse_schema

from .base_handler import BaseFileHandler


class AvroHandler(BaseFileHandler):
    """Handler for Avro files"""

    def __init__(self, filepath: Path = None, schema: Dict = None):
        super().__init__(filepath)
        self.schema = schema

    def read(self, filepath: Path = None) -> List[Dict[str, Any]]:
        """Read entire Avro file"""

        path = filepath if filepath else self.filepath

        if not path or not path.exists():
            raise FileNotFoundError(f"File not found: {path}")

        data = []
        with open(path, "rb") as f:
            avro_reader = reader(f)
            for record in avro_reader:
                data.append(dict(record))

        return data

    def write(
        self, data: List[Dict[str, Any]], filepath: Path = None, schema: Dict = None
    ) -> None:
        """
        Write data to Avro file

        """

        path = filepath if filepath else self.filepath

        avro_schema = schema or self.schema

        if not avro_schema:
            avro_schema = self.infer_schema(data[0], "AutoGeneratedRecord")

        path.parent.mkdir(parents=True, exist_ok=True)

        # Parse schema
        parsed_schema = parse_schema(avro_schema)

        with open(path, "wb") as f:
            writer(f, parsed_schema, data)

    def read_chunks(
        self, filepath: Path = None, chunk_size: int = 1000
    ) -> Iterator[List[Dict[str, Any]]]:
        """Read Avro file in chunks"""

        path = filepath if filepath else self.filepath

        if not path or not path.exists():
            raise FileNotFoundError(f"File not found: {path}")

        chunk = []
        with open(path, "rb") as f:
            avro_reader = reader(f)
            for record in avro_reader:
                chunk.append(dict(record))

                if len(chunk) >= chunk_size:
                    yield chunk
                    chunk = []

        # Yield remaining records
        if chunk:
            yield chunk

    def infer_schema(self, record: Dict[str, Any], name: str = "Record") -> Dict:
        """Auto-generate Avro schema from a record"""
        fields = []

        for key, value in record.items():
            if isinstance(value, bool):
                avro_type = "boolean"
            elif isinstance(value, int):
                avro_type = "int"
            elif isinstance(value, float):
                avro_type = "float"
            elif isinstance(value, str):
                avro_type = "string"
            elif isinstance(value, list):
                avro_type = {"type": "array", "items": "string"}
            elif isinstance(value, dict):
                avro_type = {"type": "map", "values": "string"}
            elif value is None:
                avro_type = ["null", "string"]
            else:
                avro_type = "string"

            fields.append({"name": key, "type": avro_type})

        return {"type": "record", "name": name, "fields": fields}

    @staticmethod
    def create_schema(name: str, fields: List[Dict[str, str]]) -> Dict:
        """
        Helper method to create Avro schema

        Example:
            schema = AvroHandler.create_schema("Product", [
                {"name": "id", "type": "int"},
                {"name": "title", "type": "string"},
                {"name": "price", "type": "float"}
            ])
        """
        return {"type": "record", "name": name, "fields": fields}


def main():
    """Test Avro handler"""

    print("=" * 80)
    print("AVRO HANDLER - TESTING")
    print("=" * 80)

    # Create test data
    test_data = [
        {"id": 1, "name": "Product A", "price": 100.5, "stock": 50, "active": True},
        {"id": 2, "name": "Product B", "price": 200.75, "stock": 30, "active": True},
        {"id": 3, "name": "Product C", "price": 50.25, "stock": 100, "active": False},
        {"id": 4, "name": "Product D", "price": 150.0, "stock": 20, "active": True},
    ]

    # Define schema
    schema = AvroHandler.create_schema(
        "Product",
        [
            {"name": "id", "type": "int"},
            {"name": "name", "type": "string"},
            {"name": "price", "type": "float"},
            {"name": "stock", "type": "int"},
            {"name": "active", "type": "boolean"},
        ],
    )

    handler = AvroHandler(schema=schema)

    # Test write
    print("\n→ Writing test data to Avro...")
    test_file = Path("data/test/test_products.avro")
    handler.write(test_data, test_file, schema)
    print(f"  ✓ Written to {test_file}")
    print(f"  File size: {handler.get_file_size_mb(test_file):.4f} MB")

    # Test read
    print("\n→ Reading Avro...")
    data = handler.read(test_file)
    print(f"  ✓ Read {len(data)} records")
    print(f"  First record: {data[0]}")

    # Test filter
    print("\n→ Filtering (price > 100)...")
    filtered = handler.filter(data, lambda x: x["price"] > 100)
    print(f"  ✓ Found {len(filtered)} records")
    for item in filtered:
        print(f"    • {item['name']}: ${item['price']}")

    # Test aggregations
    print("\n→ Aggregations on 'price' column...")
    print(f"  • Sum:   ${handler.aggregate(data, 'price', 'sum'):.2f}")
    print(f"  • Count: {handler.aggregate(data, 'price', 'count')}")
    print(f"  • Min:   ${handler.aggregate(data, 'price', 'min'):.2f}")
    print(f"  • Max:   ${handler.aggregate(data, 'price', 'max'):.2f}")
    print(f"  • Avg:   ${handler.aggregate(data, 'price', 'avg'):.2f}")

    # Test sorting
    print("\n→ Sorting by price (DESC)...")
    sorted_data = handler.sort(data, "price", reverse=True)
    for item in sorted_data:
        print(f"  • {item['name']}: ${item['price']}")

    # Test streaming
    print("\n→ Streaming (chunk_size=2)...")
    chunk_count = 0
    for chunk in handler.read_chunks(test_file, chunk_size=2):
        chunk_count += 1
        print(f"  Chunk {chunk_count}: {len(chunk)} records")

    # Test auto-schema inference
    print("\n→ Testing auto-schema inference...")
    auto_schema = handler.infer_schema(test_data[0], "AutoProduct")
    print(f"  ✓ Generated schema:")
    import json

    print(json.dumps(auto_schema, indent=2))

    print("\n✅ AVRO HANDLER TEST COMPLETE!")


if __name__ == "__main__":
    main()
